---
ID: "c880be49-9954-492c-9ea4-ac39abaa6013"
Parent: "93646a3b-c296-42bb-9cae-1915a53e1aaa"
Template: "93646a3b-c296-42bb-9cae-1915a53e1aaa"
Path: /sitecore/templates/Feature/About/About Item/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{93646A3B-C296-42BB-9CAE-1915A53E1AAA}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <p
          key="content"
          uid="{69B0BA3B-0B15-4A70-AB57-07CA60800E18}"
          md="{B1A97A7F-AF68-4722-8573-959F617052A0}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180806T104459Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "c489ac2c-84b0-4c0d-88dc-f7bb9d8e89ba"
      Hint: Title
      Value: $name
