---
ID: "53fa446b-54c1-4107-8c24-575dead81f27"
Parent: "b4b8f7a2-f53f-4be4-98ea-87d7fa783e0d"
Template: "b4b8f7a2-f53f-4be4-98ea-87d7fa783e0d"
Path: /sitecore/templates/Feature/Contact/Contact Container/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180808T180544Z
    - ID: "4458b5fc-795b-4f6e-9f43-1094006d25bc"
      Hint: Subtitle
      Value: Lorem ipsum dolor sit amet consectetur.
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a1754329-13dc-4d3b-903f-cd7af461eae3"
      Hint: Title
      Value: CONTACT US
